name: Atualizar Preços de Jogos

on:
  workflow_dispatch: # Permite disparar o workflow manualmente
  schedule:
    - cron: '*/5 * * * *' # Roda o script uma vez por dia à meia-noite (UTC)

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Ou a versão que você preferir

    - name: Instalar Dependências Python
      run: |
        pip install -r requirements.txt

    - name: Executar Scraper
      env:
        GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
        GSPREAD_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GSPREAD_SERVICE_ACCOUNT_CREDENTIALS }}
      run: python scraper.py # Substitua "scraper.py" pelo nome do seu arquivo Python
